uat: &uat
    '': 123456 # password but no username
    no_password: '' # username but no password
    nonexistinguser: ef
    stest12408: 1 # EC 2.0
    stest13371: 1 # EC 2.0 cool PSQ
    stest13383: 1 # EC 2.0 mini
    stest13378: 1 # EC 1.0 cool
    stest13060: 1 # EC 2.0 cool
    stest13149: 1 # EC 2.0 cool
    stest13483: 1 # EC mini which is studying high level current app doesn't support


dev: &dev
    <<: *uat
    '': 123456 # password but no username
    no_password: '' # username but no password

qa:
    nonexistinguser: badpassword

live:
    mtestc95: 1 #v1 B2B account

